name: NPM publish reusable workflow

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  npm-publish:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Installing packages
        run: yarn --frozen-lockfile
      # - name: Build Style Dictionary
      #   #   run: yarn build
      #   # - name: Setting up git config before publish
      #   run: |
      #     git config --global user.email "noreply@cbinsights.com"
      #     git config --global user.name "CBI Github CI"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.token }}
        run: npx semantic-release --dry-run
      # - name: Generate Storybook Documentation
      #   run: yarn comp:docs
      # - name: Publish to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #   if: contains('refs/heads/master', github.ref)
